name: Sync Crowdin

on:
  push:
    branches:
      - master
    paths:
      - 'app/src/main/res/values/strings.xml'
      - 'app/src/main/res/values-*/strings.xml'
      - 'crowdin.yml'
  workflow_dispatch:

concurrency:
  group: crowdin-sync
  cancel-in-progress: false

jobs:
  upload:
    name: Upload sources and translations
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Upload to Crowdin
        uses: crowdin/github-action@8f01d54f70f1713ee3f09d82c2bbb2daeac28689 # v2.17.1
        with:
          upload_sources: true
          upload_translations: true
          import_eq_suggestions: true
          auto_approve_imported: false
          download_translations: false
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
